name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  build:
    name: Lint and Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 19]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node ${{matrix.node_version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.version}}

      - name: install npm dependencies
        run: npm install

      - name: run typecheck
        run: npm run typecheck

      - name: run test
        run: npm run test
